version: '3.8'

services:
  frontend:
    image: sermalenk/skypro-front:base
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
    - "5432:5432"
    networks:
      - db-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      /bin/sh -c "python manage.py makemigrations
      &&python manage.py migrate
      &&python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .env:/app/.env #new
    networks:
      - app-network
      - db-network

volumes:
  postgres_data:

networks:
  app-network:
  db-network: