version: '3.8'

services:
  front:
    image: samischikhin/goalplanner_front:latest
    ports:
      - "80:4200"
    depends_on:
      - api

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
#    env_file:
#      - ./goalplanner/.env

  api:
    image: samischikhin/skypro-todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      /bin/sh -c "python manage.py migrate
      &&python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
