version: '3.8'

services:
  front:
    build:
      context: todolist_front
      dockerfile: Dockerfile
#    image: goalplanner_front
    ports:
      - "80:4200"
    depends_on:
      - api
    volumes:
      - .env:/app/.env #new
#    network_mode: "host"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
    - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      /bin/sh -c "python manage.py makemigrations
      &&python manage.py migrate
      &&python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .env:/app/.env #new
#    network_mode: "host"

volumes:
  postgres_data:
