# Generated by Django 4.0.1 on 2022-05-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользлватель', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
