version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    hostname: 0.0.0.0
    ports:
    - "5432:5432"
#    network_mode: "host"
volumes:
  postgres_data:
